version: '3.8'

services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - message-service_rabbitmq_network
    restart: always

networks:
  message-service_rabbitmq_network:
    external: true
