version: '3.8'

services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@et2xa97ns8rti1vt_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=duoc_fullstack
      - spring.datasource.password="Eduardocr#2610"
    networks:
      - kafka_kafka-net
    restart: always

networks:
  kafka_kafka-net:
    external: true
